# deploy.yml
name: Deploy python js App to ECR # name

on:
  workflow_dispatch: 
    
jobs:
    build:
        name: Build Image # build name
        runs-on: ubuntu-latest # build os

        steps: # sequence of tasks to be executed
            - name: Check out code 
            # Check the Dockerfile to build the docker image
              uses: actions/checkout@v2
            
            - name: Configure AWS credentials 
            # Programmatic authentication to aws
              uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                    aws-access-key-id: $AWS_ACCESS_KEY
                    aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
                    aws-region: $AWS_REGION

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag, and push image to Amazon ECR 
            # the docker image, and pushing it to ECR.
              env:
                ECR_REGISTRY: 036174619429.dkr.ecr.ap-southeast-2.amazonaws.com
                ECR_REPOSITORY: fishknowconnect
                IMAGE_TAG: latest
              run: |
                docker buildx build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend/.
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG